language: python
branches: 
  only:
    - develop
    - master

install:

	pip install -r requirements.txt
	pip install -r dev-requirements.txt
python:
  - "2.7"

services:
	- mongodb
	- sleep 15


script: py.test