language: python

python:
  - "3.4"

branches: 
  - develop
  - master
  - api-prototype

install:
  - pip install -r requirements.txt
  - npm install -g bower
  - bower install --allow-root

services:
  - postgres: "9.3"
  - sleep 15

before_script:
  - psql -c 'create database deskdb;' -U postgres
  - psql -c "CREATE USER deskuser password '123123'" -U postgres -d deskdb
  
script: py.test
