language: python

python:
  - "3.4"

branches: 
    - develop
    - master
    - api-prototype

install:
    pip install -r requirements.txt

services:
    - postgres: "9.3"
    - sleep 15

script: py.test